- Generating backend, Refactoring prototype. - There is an error in service or web module: java.lang.NoClassDefFoundError: com/liferay/docs/guestbook/model/Guestbook The @Referenced/generated guestbook model is missing dunno why